export interface MockConta {
  id: string;
  fornecedor: string;
  valor: number;
  discriminacao: string | null;
  dataVencimento: Date;
  dataPagamento: Date | null;
  valorPago: number | null;
  status: "PENDENTE" | "PAGA" | "VENCIDA" | "CANCELADA";
  categoria: "CUSTEIO" | "INVESTIMENTO" | "OUTRAS";
  observacao: string | null;
  usuarioId: string;
  usuario?: { nome: string };
  createdAt: Date;
}

export interface MockEntrada {
  id: string;
  descricao: string;
  valor: number;
  dataEntrada: Date;
  tipo: "MANUAL" | "VENDA" | "OUTROS";
  observacao: string | null;
  usuarioId: string;
  usuario?: { nome: string };
  createdAt: Date;
}

// In-Memory Store persistente durante a sessão do servidor
declare global {
  // eslint-disable-next-line no-var
  var mockContasGlobal: MockConta[] | undefined;
  // eslint-disable-next-line no-var
  var mockEntradasGlobal: MockEntrada[] | undefined;
}

export const defaultMockContas: MockConta[] = [
  {
    id: "conta-1",
    fornecedor: "Climatizar (Edgar)",
    valor: 540.95,
    discriminacao: "Conserto Ar Condicionado",
    dataVencimento: new Date(2026, 6, 5),
    dataPagamento: new Date(2026, 6, 5),
    valorPago: 540.95,
    status: "PAGA",
    categoria: "CUSTEIO",
    observacao: "Parcela 1/6 recorrente",
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-2",
    fornecedor: "MP Refricenterse (Luciene)",
    valor: 400.0,
    discriminacao: "Cervejeiro / Geladeiras",
    dataVencimento: new Date(2026, 6, 8),
    dataPagamento: new Date(2026, 6, 8),
    valorPago: 400.0,
    status: "PAGA",
    categoria: "INVESTIMENTO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-3",
    fornecedor: "R Center Outlet (Luciene)",
    valor: 400.08,
    discriminacao: "Expositor Térmico",
    dataVencimento: new Date(2026, 6, 10),
    dataPagamento: new Date(2026, 6, 10),
    valorPago: 400.08,
    status: "PAGA",
    categoria: "INVESTIMENTO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-4",
    fornecedor: "Supergasbras",
    valor: 114.9,
    discriminacao: "Botijão de Gás P45 Cozinha",
    dataVencimento: new Date(2026, 6, 12),
    dataPagamento: new Date(2026, 6, 12),
    valorPago: 114.9,
    status: "PAGA",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-5",
    fornecedor: "Edilberto Vigano",
    valor: 1532.0,
    discriminacao: "Aluguel Ponto Comercial",
    dataVencimento: new Date(2026, 6, 10),
    dataPagamento: new Date(2026, 6, 10),
    valorPago: 1532.0,
    status: "PAGA",
    categoria: "CUSTEIO",
    observacao: "Transferência bancária",
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-6",
    fornecedor: "Assai Atacadista",
    valor: 4320.5,
    discriminacao: "Insumos Gerais e Alimentos",
    dataVencimento: new Date(2026, 6, 6),
    dataPagamento: new Date(2026, 6, 6),
    valorPago: 4320.5,
    status: "PAGA",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-7",
    fornecedor: "Aliança Carnes",
    valor: 5120.0,
    discriminacao: "Carnes Bovinas e Cortes Especiais",
    dataVencimento: new Date(2026, 6, 15),
    dataPagamento: new Date(2026, 6, 15),
    valorPago: 5120.0,
    status: "PAGA",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-8",
    fornecedor: "Bom Preço Hortifruti",
    valor: 1350.0,
    discriminacao: "Verduras, Legumes e Temperos",
    dataVencimento: new Date(2026, 6, 14),
    dataPagamento: new Date(2026, 6, 14),
    valorPago: 1350.0,
    status: "PAGA",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-9",
    fornecedor: "Supermercado Pires",
    valor: 1180.4,
    discriminacao: "Laticínios e Mercearia",
    dataVencimento: new Date(2026, 6, 18),
    dataPagamento: new Date(2026, 6, 18),
    valorPago: 1180.4,
    status: "PAGA",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-10",
    fornecedor: "Fort Atacadista",
    valor: 920.25,
    discriminacao: "Material de Limpeza e Descartáveis",
    dataVencimento: new Date(2026, 6, 20),
    dataPagamento: new Date(2026, 6, 20),
    valorPago: 920.25,
    status: "PAGA",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-11",
    fornecedor: "Casa do Porco",
    valor: 1680.0,
    discriminacao: "Suínos e Embutidos Artesanais",
    dataVencimento: new Date(2026, 6, 22),
    dataPagamento: new Date(2026, 6, 22),
    valorPago: 1680.0,
    status: "PAGA",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-12",
    fornecedor: "Stephany dos Santos",
    valor: 890.0,
    discriminacao: "Embalagens Marmitex Delivery",
    dataVencimento: new Date(2026, 6, 23),
    dataPagamento: new Date(2026, 6, 23),
    valorPago: 890.0,
    status: "PAGA",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-13",
    fornecedor: "Juan Gabriel (PDV)",
    valor: 250.0,
    discriminacao: "Sistema PDV Frente de Caixa",
    dataVencimento: new Date(2026, 6, 25),
    dataPagamento: new Date(2026, 6, 25),
    valorPago: 250.0,
    status: "PAGA",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-14",
    fornecedor: "Vivo/Telefônica",
    valor: 189.9,
    discriminacao: "Internet Fibra Restaurante",
    dataVencimento: new Date(2026, 6, 25),
    dataPagamento: new Date(2026, 6, 25),
    valorPago: 189.9,
    status: "PAGA",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-15",
    fornecedor: "Energia Elétrica",
    valor: 2789.68,
    discriminacao: "Conta de Luz Restaurante",
    dataVencimento: new Date(2026, 6, 26),
    dataPagamento: new Date(2026, 6, 26),
    valorPago: 2789.68,
    status: "PAGA",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-16",
    fornecedor: "Água e Esgoto",
    valor: 790.0,
    discriminacao: "Consumo de Água",
    dataVencimento: new Date(2026, 6, 27),
    dataPagamento: new Date(2026, 6, 27),
    valorPago: 790.0,
    status: "PAGA",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  // Contas Pendentes
  {
    id: "conta-17",
    fornecedor: "Aliança Carnes",
    valor: 2850.0,
    discriminacao: "Pedido Semanal Carnes Churrasco",
    dataVencimento: new Date(2026, 6, 28),
    dataPagamento: null,
    valorPago: null,
    status: "PENDENTE",
    categoria: "CUSTEIO",
    observacao: "Boleto aguardando liberação",
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-18",
    fornecedor: "Frutaria da Julio",
    valor: 740.0,
    discriminacao: "Frutas Sobremesas e Sucos",
    dataVencimento: new Date(2026, 6, 29),
    dataPagamento: null,
    valorPago: null,
    status: "PENDENTE",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-19",
    fornecedor: "Facebook/Instagram Ads",
    valor: 450.0,
    discriminacao: "Anúncios Meta Delivery",
    dataVencimento: new Date(2026, 6, 30),
    dataPagamento: null,
    valorPago: null,
    status: "PENDENTE",
    categoria: "OUTRAS",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-20",
    fornecedor: "Google Ads",
    valor: 350.0,
    discriminacao: "Anúncios Busca Local",
    dataVencimento: new Date(2026, 6, 30),
    dataPagamento: null,
    valorPago: null,
    status: "PENDENTE",
    categoria: "OUTRAS",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-21",
    fornecedor: "Manutenção Coifa e Fogão",
    valor: 496.84,
    discriminacao: "Limpeza de Dutos e Queimadores",
    dataVencimento: new Date(2026, 6, 31),
    dataPagamento: null,
    valorPago: null,
    status: "PENDENTE",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "conta-22",
    fornecedor: "Assai Atacadista",
    valor: 3000.0,
    discriminacao: "Reposição Estoque Fim de Mês",
    dataVencimento: new Date(2026, 6, 31),
    dataPagamento: null,
    valorPago: null,
    status: "PENDENTE",
    categoria: "CUSTEIO",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
];

export const defaultMockEntradas: MockEntrada[] = [
  {
    id: "entrada-1",
    descricao: "Vendas Almoço Balcão e Buffet (Semana 1)",
    valor: 9450.0,
    dataEntrada: new Date(2026, 6, 7),
    tipo: "VENDA",
    observacao: "Dinheiro e PIX",
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "entrada-2",
    descricao: "Vendas Almoço Balcão e Buffet (Semana 2)",
    valor: 11200.0,
    dataEntrada: new Date(2026, 6, 14),
    tipo: "VENDA",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "entrada-3",
    descricao: "Vendas Delivery e Marmitex (Semana 3)",
    valor: 8900.0,
    dataEntrada: new Date(2026, 6, 21),
    tipo: "VENDA",
    observacao: null,
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "entrada-4",
    descricao: "Aporte de Caixa Fundo de Giro",
    valor: 3500.0,
    dataEntrada: new Date(2026, 6, 2),
    tipo: "MANUAL",
    observacao: "Reserva de sócios",
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
  {
    id: "entrada-5",
    descricao: "Vendas Balcão Almoço Hoje",
    valor: 1850.0,
    dataEntrada: new Date(),
    tipo: "VENDA",
    observacao: "Movimento do almoço",
    usuarioId: "admin-default-id",
    usuario: { nome: "Dona Vó Admin" },
    createdAt: new Date(),
  },
];

export function getMockContas(): MockConta[] {
  if (!globalThis.mockContasGlobal) {
    globalThis.mockContasGlobal = [...defaultMockContas];
  }
  return globalThis.mockContasGlobal;
}

export function getMockEntradas(): MockEntrada[] {
  if (!globalThis.mockEntradasGlobal) {
    globalThis.mockEntradasGlobal = [...defaultMockEntradas];
  }
  return globalThis.mockEntradasGlobal;
}
